CREATE DATABASE `laravel_test` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;

GRANT ALL PRIVILEGES ON laravel_test.* TO 'gio'@'%' WITH GRANT OPTION;

